Models/Training.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Engineer_MVC.Models
{
    public class Training
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }

        [Required]
        public float Duration { get; set; }
        [Required]
        public float Price { get; set; }
        [Required]
        public string Status { get; set; }
        [Required]
        public int UsersNumber { get; set; } 
        public int TreatmentId { get; set; }
        public Treatment Treatment { get; set; } 
        public string? EmployeeId { get; set; }
        [ForeignKey("EmployeeId")]
        public User? Employee { get; set; } 
        public ICollection<User>? Users { get; set; } 
        public ICollection<RatingForTraining>? Ratings { get; set; }
        public ICollection<CancellationRequest>? Requests { get; set; }
        [NotMapped]
        public DateTime EndTime => Date.AddMinutes(Duration);
    }
}

Models/ViewModels/TrainingsViewModel.cs
namespace Engineer_MVC.Models.ViewModels
{
    public class TrainingsViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public float Cost { get; set; }
        public string NumberUsers { get; set; }
        public string EmployeeBackgroundColor { get; set; }
        public string Employee { get; set; }
        public string EmployeeId { get; set; }
        public int TreatmentId { get; set; }
        
    }
}

Controllers/TrainingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Engineer_MVC.Data;
using Engineer_MVC.Models;
using Engineer_MVC.Models.Templates;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Data;
using Engineer_MVC.Data.Interfaces;
using Microsoft.Extensions.Localization;
using Engineer_MVC.Data.Services;
using System.ComponentModel.DataAnnotations;
using Engineer_MVC.Models.ViewModels;
using Newtonsoft.Json;
using Microsoft.Extensions.Hosting;
using System.Security.Claims;
using Microsoft.AspNetCore.Localization;
using RazorLight;

namespace Engineer_MVC.Controllers
{
    public class TrainingsController : Controller
    {
        private readonly EngineerContext _context;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IEmailSender _emailSender;
        private readonly IStringLocalizer<SharedResource> _sharedResource;
        private readonly IUserService _userService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public TrainingsController(EngineerContext context,
            IWebHostEnvironment hostEnvironment,
            UserManager<User> userManager,
            RoleManager<IdentityRole> roleManager,
            IEmailSender emailSender,
            IStringLocalizer<SharedResource> sharedResource,
            IUserService userService)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
            _emailSender = emailSender;
            _sharedResource = sharedResource;
            _userService = userService;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Trainings
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> UpdateSelects(string selectedTreatmentType, string employeeId, int trainingId)
        {
            var user = await _userManager.FindByIdAsync(employeeId);
            var userWithTreatments = await _context.Users
                .Include(u => u.Treatments)
                .FirstOrDefaultAsync(u => u.Id == user.Id);
            var treatmentTypesForEmployees = userWithTreatments.Treatments.Select(t => t.Type).Distinct().ToList();
            var treatmentNamesForEmployees = userWithTreatments.Treatments.Select(t => t.Name).ToList();
            if (selectedTreatmentType != "all" && selectedTreatmentType != null)
            {
                treatmentNamesForEmployees = treatmentNamesForEmployees
                    .Where(name => _context.Treatment.Any(t => t.Name == name && t.Type == selectedTreatmentType))
                    .Distinct()
                    .ToList();
                ViewBag.Types = treatmentTypesForEmployees;
                ViewBag.Names = treatmentNamesForEmployees;
            }
            var training = _context.Training.Include(t => t.Users).FirstOrDefault(t => t.Id == trainingId);
            var UserCounts = training.Users?.Count() ?? 0;
            ViewBag.UsersCount = UserCounts;
            return Json(new
            {
                TreatmentTypes = treatmentTypesForEmployees,
                TreatmentNames = treatmentNamesForEmployees,
                UsersCount = UserCounts
            });
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> TrainingList()
        {
            var usersDictionary = await _context.Users.ToDictionaryAsync(u => u.Id, u => u.FullName);
            ViewBag.Users = usersDictionary;

            var trainingsList = _context.Training.Include(t => t.Users).Include(t => t.Employee).Include(t => t.Treatment).Where(t => t.Status == "To Do").OrderBy(t => t.Date).ToList();
            var treatmentTypes = _context.Treatment.Select(t => t.Type).Distinct().ToList();
            var treatmentNames = _context.Treatment.Select(t => t.Name).ToList();

            ViewBag.Types = treatmentTypes;
            ViewBag.Names = treatmentNames;
            ViewBag.UsersCount = 0;
            ViewBag.SharedResourceTranslations = JsonConvert.SerializeObject(_sharedResource.GetAllStrings());
            return View(trainingsList);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TrainingList([FromForm] Training training)
        {
            var employee = await _userManager.FindByIdAsync(training.EmployeeId);
            var users = _context.Users.Include(t => t.Treatments)
                .Include(u => u.TrainingsReceive)
                .ToList();
            var selectedUsers = users
            .Where(u => u.TrainingsReceive.Any(tr => tr.Id == training.Id))
            .ToList();

            if (employee != null)
            {
                training.Employee = employee;
                training.Treatment = _context.Treatment.FirstOrDefault(t => t.Name == training.Treatment.Name && t.Type == training.Treatment.Type);
                training.TreatmentId = training.Treatment.Id;

                _context.ChangeTracker.Clear();
                training.Users.Clear();
                training.Users = selectedUsers;
                var validationResults = new List<ValidationResult>();
                if (!Validator.TryValidateObject(training, new ValidationContext(training), validationResults, true))
                {
                    foreach (var validationResult in validationResults)
                    {
                        ModelState.AddModelError("", validationResult.ErrorMessage);
                    }
                }
                else
                {
                    var local = _context.Set<Training>()
                    .Local
                    .FirstOrDefault(entry => entry.Id.Equals(training.Id));

                    // check if local is not null 
                    if (local != null)
                    {
                        // detach
                        _context.Entry(local).State = EntityState.Detached;
                    }
                    // set Modified flag in your entry
                    _context.Entry(training).State = EntityState.Modified;



                    training.Status = "Done";
                    _context.Update(training);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("TrainingList");
                }

            }
            {
                ModelState.AddModelError("UserId", "Nieprawidłowy użytkownik.");
            }

            ViewBag.Types = await _context.Treatment.Select(t => t.Type).Distinct().ToListAsync();
            ViewBag.Names = await _context.Treatment.Select(t => t.Name).Distinct().ToListAsync();
            ViewBag.UsersCount = 0;
            return RedirectToAction("TrainingList");
        }

        public async Task<IActionResult> ChangeToCanceled(int trainingId, string userId)
        {
            var training = _context.Training.Include(t => t.Users).Include(t => t.Treatment).FirstOrDefault(t => t.Id == trainingId);
            var user = await _userManager.FindByIdAsync(userId);

            if (training != null)
            {
                var existingRequest = _context.CancellationRequest.FirstOrDefault(r => r.TrainingId == trainingId && r.UserId == userId);

                if (existingRequest == null)
                {
                    var request = new CancellationRequest
                    {
                        TrainingId = trainingId,
                        UserId = userId,
                        IsCanceled = true
                    };
                    _context.CancellationRequest.Add(request);
                }
                else
                {
                    existingRequest.IsCanceled = true;
                }

                _context.SaveChanges();
            }

            var templatePath = "Views/Templates/ParticipationTrainingRequestTemplate.cshtml";
            var template = System.IO.File.ReadAllText(templatePath).ToString();
            var translationTemplate = new TranslationTemplate(_context, _hostEnvironment, _sharedResource);
            var translatedTemplateResult = translationTemplate.Translate(template);

            var translatedTemplate = ((ContentResult)translatedTemplateResult).Content;

            var engine = new RazorLightEngineBuilder()
                .UseMemoryCachingProvider()
                .Build();

            var model = new AppointmentEmailModel
            {
                Employee = training.Employee.FullName,
                Treatment = $"{_sharedResource[training.Treatment.Type]} {_sharedResource[training.Treatment.Name]}",
                StartDate = training.Date,
                EndDate = training.EndTime,
                Price = training.Price
            };

            var resultTemplate = await engine.CompileRenderStringAsync("templateKey", translatedTemplate, model, null);
            var message = new Message(new string[] { user.Email }, _sharedResource["ParticipationTraining"], resultTemplate);
            _emailSender.SendEmailAsync(message);

            return RedirectToAction("Index", "home");
        }
        public async Task<IActionResult> ChangeToNotCanceled(int trainingId, string userId)
        {
            var training = _context.Training.Include(t => t.Users).Include(t => t.Treatment).FirstOrDefault(t => t.Id == trainingId);
            var user = await _userManager.FindByIdAsync(userId);
            if (training != null)
            {
                var existingRequest = _context.CancellationRequest.FirstOrDefault(r => r.TrainingId == trainingId && r.UserId == userId);

                if (existingRequest == null)
                {

Views/Trainings/CalendarClient.cshtml
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='utf-8' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' rel='stylesheet'>
    <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
    <script src='fullcalendar/core/index.global.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/locales-all.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-md-3 d-flex align-items-center">
            <div class="navigation-container">
                <h2 class="navigation-header">@sharedResource["Navigation"]</h2>
                <div class="navigation-links">
                    <a asp-controller="Appointments" asp-action="Calendar" class="navigation-link "> @sharedResource["CalendarAppointments"]</a>
                    <a asp-controller="Trainings" asp-action="CalendarClient" class="navigation-link active"> @sharedResource["CalendarTrainings"]</a>
                </div>
            </div>
        </div>
        <div class="col-md-9 mt-4">
            <div id='calendar' class="calendar-box"></div>
            <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="eventModalLabel">@sharedResource["YourTraining"]</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div id="eventModalContent">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var sharedResource = JSON.parse(`@Html.Raw(ViewBag.SharedResourceTranslations)`);
        var initialLocaleCode = '@Html.Raw(ViewBag.language)';
        var allEvents = []; // Tablica do przechowywania wszystkich wydarzeń
        var calendar;
        document.addEventListener('DOMContentLoaded', function () {
            updateTrainings();
            initializeCalendar();
        });
        function initializeCalendar() {
            var calendarEl = document.getElementById('calendar');
            calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'timeGridWeek',
                headerToolbar: {
                    left: 'dayGridMonth,timeGridWeek,timeGridDay',
                    center: 'title',
                    right: 'today prev,next'
                },
                locale: initialLocaleCode,
                slotMinTime: "06:00",
                slotMaxTime: "24:00",
                firstDay: 1,
                events: allEvents,
                eventClick: function (info) {
                    // Wywołaj funkcję do obsługi kliknięcia na event
                    handleEventClick(info.event);
                }
            });
            calendar.render();
        }
        function handleEventClick(event) {
            handleSingleEventClick(event);

        }
        function handleSingleEventClick(event) {
            console.log(event);
            var title = event.title;
            var startTime = new Date(event.start);
            var endTime = new Date(event.end);
            var employee = event.extendedProps.employee;
            var treatmentId = event.treatmentId;
            var employeeId = event.employeeId;
            var cost = event.extendedProps.cost;
            var numberusers = event.extendedProps.numberusers;
            var trainingId = event.id;
            var startTimeFormatted = startTime.toLocaleString('pl-PL', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });

            var endTimeFormatted = endTime.toLocaleTimeString('pl-PL', { hour: '2-digit', minute: '2-digit' });

            var startFunction = event.start;
            var endFunction = event.end;
            var content = `
                                                                            <div class="carousel-inner">
                                                                                <div class="carousel-item active">
                                                                                  <div class="form-group">
                                            <label class="control-label">@sharedResource["Training"]</label>
                                    <input type="text" class="form-control" value="${title}" disabled />
                                </div>
                                <div class="form-group">
                                                    <label class="control-label">@sharedResource["TrainingDate"]</label>
                                    <input type="text" class="form-control" value="${startTimeFormatted}-${endTimeFormatted}" disabled />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">@sharedResource["Cost"]</label>
                                    <input type="text" class="form-control" value="${cost} euro" disabled />
                                </div>
                                <div class="form-group">
                                    <label class="control-label">@sharedResource["Employee"]</label>
                                    <input type="text" class="form-control" value="${employee}" disabled />
                                </div>
                                        <div class="form-group">
                                            <label class="control-label">@sharedResource["ParticipantsList"]</label>
                                            <input type="text" class="form-control" value="${numberusers}" disabled />
                                        </div>
                       <button class="button btn-info d-flex justify-content-center" onclick="window.location.href='/Trainings/SignUpTraining?trainingId=${trainingId}'" class="btn btn-primary">@sharedResource["Confirm"]</button>
                                                                                </div>

                                                                             </div>
                                                                        `;
            document.getElementById('eventModalContent').innerHTML = content;
            var eventModal = new bootstrap.Modal(document.getElementById('eventModal'));
            eventModal.show();
        }
        function updateTrainings() {
            var trainings = @Html.Raw(Json.Serialize(Model));

            for (var i = 0; i < trainings.length; i++) {
                var start = moment(trainings[i].startDate).format();
                var end = moment(trainings[i].endDate).format();
                var backgroundColor = trainings[i].userBackgroundColor;
                var title = trainings[i].title;
                var cost = trainings[i].cost;
                var employee = trainings[i].employee;
                var numberusers = trainings[i].numberUsers;
                var id = trainings[i].id;
                console.log(id);
                allEvents.push({
                    title: title,
                    start: start,
                    end: end,
                    cost: cost,
                    employee: employee,
                    numberusers: numberusers,
                    backgroundColor: backgroundColor,
                    id: id
                });
            }
        }
    </script>
</body>

Views/Trainings/Create.cshtml
@model Engineer_MVC.Models.Training

<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<main>
    <div class="row">
        <div class="col-md-3 d-flex align-items-center">
            <div class="navigation-container">
                <h2 class="navigation-header">@sharedResource["Navigation"]</h2>
                <div class="navigation-links">
                    <a asp-action="TrainingList" class="navigation-link"> @sharedResource["TrainingList"]</a>
                    <a asp-action="Create" class="navigation-link active ms-3"> @sharedResource["CreateTraining"]</a>
                    <a asp-action="Calendar" class="navigation-link"> @sharedResource["Calendar"]</a>
                    <a asp-action="DoneTrainings" class="navigation-link"> @sharedResource["Archives"]</a>
                    <a asp-action="CancelTrainings" class="navigation-link"> @sharedResource["Requests"]</a>
                </div>
            </div>
        </div>
        <div class="col-md-9 mt-4">
            <form asp-action="Create" class="create-post gap-3">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["TrainingDate"]</label>
                    <input asp-for="Date" class="title-input" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["Duration"]</label>
                    <input asp-for="Duration" class="title-input" />
                    <span asp-validation-for="Duration" class="text-danger"></span>
                </div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["Cost"]</label>
                    <input asp-for="Price" class="title-input" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["Status"]</label>
                    <select asp-for="Status" class="select-container">
                        <option value="To Do">@sharedResource["ToDo"]</option>
                        <option value="Done">@sharedResource["Done"]</option>
                    </select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["NumberParticipants"]</label>
                    <input asp-for="UsersNumber" class="title-input" />
                    <span asp-validation-for="UsersNumber" class="text-danger"></span>
                </div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["Treatment"]</label>
                    <select asp-for="TreatmentId" class="select-container" asp-items="ViewBag.TreatmentId" onchange="updateEmployees()"></select>
                    <span asp-validation-for="TreatmentId" class="text-danger"></span>
                </div>
                <div class="single-box">
                    <label class="title-label">@sharedResource["TrainingProvider"]</label>
                    <select asp-for="EmployeeId" class="select-container" asp-items="ViewBag.EmployeeId"></select>
                </div>
                <div class="single-box">
                    <input type="submit" value=@sharedResource["CreateTraining"] class="create-button" />
                </div>
            </form>
        </div>
    </div>
</main>
<script>
    function updateEmployees() {
        var selectedTreatmentId = document.getElementById("TreatmentId").value;

        $.ajax({
            url: `/Trainings/GetEmployeesByTreatment?treatmentId=${selectedTreatmentId}`,
            type: "GET",
            success: function (data) {
                var employeeDropdown = document.getElementById("EmployeeId");
                while (employeeDropdown.firstChild) {
                    employeeDropdown.removeChild(employeeDropdown.firstChild);
                }
                data.employeesWithTreatment.forEach(function (employee) {
                    var option = document.createElement("option");
                    option.value = employee.id;
                    option.textContent = employee.fullName;
                    employeeDropdown.appendChild(option);
                });
            },
            error: function (xhr, status, error) {
                console.log(error);
            }
        });
    }
    document.addEventListener("DOMContentLoaded", function () {
        updateEmployees();
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trainings/Delete.cshtml
@model Engineer_MVC.Models.Training

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Training</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsersNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsersNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Treatment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Treatment.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Trainings/Details.cshtml
@model Engineer_MVC.Models.Training

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Training</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsersNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsersNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Treatment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Treatment.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Trainings/Edit.cshtml
@model Engineer_MVC.Models.Training

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Training</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ratings" class="control-label"></label>
                <input asp-for="Ratings" class="form-control" />
                <span asp-validation-for="Ratings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsersNumber" class="control-label"></label>
                <input asp-for="UsersNumber" class="form-control" />
                <span asp-validation-for="UsersNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TreatmentId" class="control-label"></label>
                <select asp-for="TreatmentId" class="form-control" asp-items="ViewBag.TreatmentId"></select>
                <span asp-validation-for="TreatmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}